# Generated by Django 4.0.4 on 2022-05-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('langage', models.CharField(max_length=100)),
                ('technos', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('lien_github', models.TextField(default='github.com', max_length=100)),
            ],
        ),
    ]
